global:
  scrape_interval: 5s          # fr√©quence de scrap des m√©triques
  evaluation_interval: 5s      # fr√©quence d'√©valuation des r√®gles

scrape_configs:
  - job_name: 'events_app'
    metrics_path: '/events/actuator/prometheus'
    static_configs:
      - targets: ['events_app:8089']   # use the container name
        labels:
          application: 'events-project'

  # üì¶ cAdvisor : m√©triques des conteneurs Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # üñ•Ô∏è Node-exporter : m√©triques de la VM / host
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # üß† Prometheus lui-m√™me
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
